### ISSUE TITLE
사이트 디자인이 깔끔해요!

### ISSUE THREAD

**Issue by jyp-on** [woorifisa-service-dev-3rd/frontend-1st-woohaengshi#14]
우리 FISA에 맞는 색깔과 깔끔한 레이아웃이 적용 되어서 눈이 편안해지네요.

1. 과목 추가 기능이 있으면 좋을 것 같아요 (아니면 과목을 본인이 직접 입력하는 형식이면 좋을 것 같아요)
2. 과목마다 타이머가 따로 작동하면 좋을 것 같아요.

**Comment by khwoowoo** [comment]
의견 감사합니다! 추후에 자바스크립트 수강 후 논의하여 검토해보도록하겠습니다!
