### ISSUE TITLE
[피드백] 우행시~! 기대가 되는 프로젝트!

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/frontend-1st-woohaengshi#15]
페이지들이 깔끔하고 ui적으로 보기가 좋은 것 같아요! 공부할 때 다 같이 쓰면 유용할거 같아서 기대가 되는 프로젝트입니다!!!
기능 추가하려면 많이 추가할 수 있고 완성도가 높아보여요! 최고!!!

1. 랭킹페이지에서 1등을 조금 더 강조하면 승부욕 자극이 더 되어 공부를 열심히 할 수 있을 것 같아요!

예시 이미지 
![image](https://github.com/user-attachments/assets/7fca4697-55bc-480c-ac17-281b49b7a5b5)

**Comment by khwoowoo** [comment]
의견 감사합니다! 이미지 참고해서 나중에 피드백 반영하도록 노력하겠습니다!
