### ISSUE TITLE
디자인 정말 잘 만드셨습니다.

### ISSUE THREAD

**Issue by bw02184** [woorifisa-service-dev-3rd/frontend-1st-woohaengshi#17]
1. 랭킹 페이지의 1등이 가운데에 있는데 2, 3등을 밑으로 살짝 내리면 더 1등 느낌 나고 좋을 거 같아요! 배포 되면 이걸로 공부 인증 열심히 해보고 싶습니다. 정말 기대됩니다~
2. 모바일에서도 사용할 수 있도록 반응형으로 만들어주시면 좋을 것 같아요! 그리고 스터디룸 예약서비스와 연동이 되면 더 유용할 것 같아요! ++  뽀모도로 타이머 이런 것도 만들어줬으면 좋겠어욤
3. Lighthouse에 seo를 올리는 방법을 자세히 설명해 주셔서 좋았습니다.

**Comment by khwoowoo** [comment]
의견 감사합니다!  랭킹 및 반응형은 디자인 레퍼런스 찾아서 한 번 반영하도록 하겠습니다!
스터디룸은 추후에 긍정적으로 검토해보겠습니다!
