### ISSUE TITLE
[강김길] UI가 인상적이어서 잘 봤습니다 !!

### ISSUE THREAD

**Issue by rlfrkdms1** [woorifisa-service-dev-3rd/frontend-1st-woohaengshi#18]
정말 잘 봤습니다. 탐나는 프로젝트인 것 같아요 😏 한가지 의견 드리겠습니다 !
- 개인별로 시간을 저장해야하는 프로젝트로 보입니다. 그렇다면, 로그인 기능이 있어야 개인별로 기록하고 관리하기 쉬울 것 같습니다. 남의 이름으로 시간을 할 수도 있고, 여러 위험 요소가 있을 것 같습니다.

**Comment by khwoowoo** [comment]
자바스크립트 수강 후 추후에 반영하도록 하겠습니다~ 의견감사합니다~
