### ISSUE TITLE
공부할 때 정말 도움이 될 것 같아요! 질문 있습니다!

### ISSUE THREAD

**Issue by my123dsa** [woorifisa-service-dev-3rd/frontend-1st-woohaengshi#19]
1. login 같은 경우는 어떻게 진행이 될까요? 추후에 추가 예정이신가요?

2. 랭킹에 업적이 추가 되었으면 좋겠습니다 (ex. 주 3회, 1시간 이상 공부 시 메달 추가, 특정분야 10시간 이상 시 메달, 매일 출석:개근상 등)

3. 달력에 분야 별로 다른 색상으로 공부한 과목이 표시되면 좋을 것 같아요! 공부한 분야를 개인페이지에서 한눈에 확인 가능할 것 같습니다!

**Comment by khwoowoo** [comment]
1. 로그인은 추가할 예정입니다!
2. 필수 기능 구현까지 완료되면 검토해보겠습니다!
3. 좋은 피드백 감사합니다! 의견 검토해보도록 하겠습니다!
