### ISSUE TITLE
인상깊게봤습니다. 추후 구현될 기능에 대해 궁금증 있습니다.

### ISSUE THREAD

**Issue by jabin1221** [woorifisa-service-dev-3rd/frontend-1st-woohaengshi#21]
재밌게 감상했습니다.
초기 화면에서 제시된 과목에 없는 다른 공부를 하거나 반대로 제시된 과목들 중에 공부하지 않을 과목도 있을 것 같은데, 과목 항목을 추가하거나 제거 할 수 있는 기능을 추가하실지 궁금합니다!

**Comment by Kong-E** [comment]
의견 감사합니다!! 과목 추가 및 제거 기능 추가하도록 하겠습니다~!
